### PR TITLE
Chrome extension

### PR DESCRIPTION
**Pull request by vanwoerden**
A little chrome extension that shows you a random care card every time you open a new tab. In need of some cleanup but it works. 

Icons and other assets to publish to the Chrome web store are not up to date.

### CODE REVIEW

**Review by ericbenwa — COMMENTED** [review]
Hi Ernst,

Thanks for putting this together.
We're thinking it may be good to place the chrome extension in its own repo (and link to it via this CC repo's readme).
What do you think about moving this code to - https://github.com/goinvo/CareCardsChromeExtension ?

**Comment by vanwoerden** [comment]
Sounds good, go ahead!

**Comment by ericbenwa** [comment]
Ok. We just moved the chrome extension over to the new repo:
https://github.com/goinvo/CareCardsChromeExtension

You may want to double-check that it still works properly and add any documentation in the README (like how to install).

Thanks!

**Comment by vanwoerden** [comment]
ok, will do! 
👍 👍 👍

**Pull request merged**
